---
language: python
cache: pip
python:
 - "3.7"
services:
  - docker

env:
  global:
    - ROLE_NAME: ansible-nvm
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: fedora31
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9

install:
  - pip install molecule yamllint ansible-lint docker flake8 testinfra

script:
  - molecule --version
  - ansible --version
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
