---
- name: Install nvm {{ nvm_version }}
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_install_path }}"
    version: "{% if nvm_version=='latest' %} master
              {% elif nvm_version|regex_search('\\d.') %} v{{ nvm_version }}
              {% else %} {{ nvm_version }}
              {% endif %}"
    force: "{{ nvm_force_install|bool }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add nvm to {{ nvm_shell_init_file }} file
  blockinfile:
    path: "{{ nvm_shell_init_file }}"
    marker: "# NVM path management from ansible {mark}"
    block: |
      . {{ nvm_install_path }}/nvm.sh
