---
- name: Install Node.js {{ nvm_node_version }}
  shell: ". ./nvm.sh && nvm install
    {% if nvm_node_version == 'lts' %} --lts
    {% elif nvm_node_version == 'latest' %} node
    {% else %}{{ nvm_node_version }}{% endif %}"
  args:
    chdir: "{{ nvm_install_path }}"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set default Node.js version to {{ nvm_node_version }}
  shell: ". ./nvm.sh && nvm alias default
    {% if nvm_node_version == 'lts' %} lts
    {% elif nvm_node_version == 'latest' %} node
    {% else %}{{ nvm_node_version }}{% endif %}"
  args:
    chdir: "{{ nvm_install_path }}"
  changed_when: False
  ignore_errors: "{{ ansible_check_mode }}"
