---
- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"
  tags: nvm

- include: setup-debian.yml
  when: ansible_os_family == "Debian"
  tags: nvm

- include: install_nvm.yml
  tags: nvm

- include: install_nodejs.yml
  tags: nvm
