---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ${MOLECULE_DISTRO:-centos7}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    diff: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
    prepare: ../common/prepare.yml
verifier:
  name: testinfra
  lint: |
    set -e
    flake8

scenario:
  name: "latest"
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
  check_sequence:
    - destroy
    - create
    - check
    - destroy
